### PR TITLE
new article: binding ports.

### PR DESCRIPTION
**Pull request by sundippatel**
Rearranged article to come before Securing your System

### CODE REVIEW

**Comment by runnabro** [comment]
Your new file name is 

> 2016-07-15-binding-docker-ports..markdown

Are the double dots on purpose?

**Comment by sundippatel** [comment]
Fixed. Good catch

**Comment by taylordolan** [comment]
image
"Connecting Multiple Instances" should be underlined. Adding the `link` class fixes it but I don't know if that's how we do things on /docker.

Also, I don't see that article anywhere.

**Comment by runnabro** [comment]
I've added styles for links, @sundippatel do you know what that link should be going to?

**Comment by sundippatel** [comment]
That link is to a future article. Removed it, and will re-add it when its ready.

**Comment by taylordolan** [comment]
image
at iPhone 5 size

**Comment by runnabro** [comment]
Added a word break, but it should only work in webkit and blink browsers.

**Pull request merged**
